### ISSUE TITLE
Issue with socket connection

### ISSUE THREAD

**Issue by chocopowwwa** [lohek/mjml-editor#27]
> > mjml-editor@0.0.1 dev /tmp/mjml-editor
> > cross-env NODE_ENV=development nodemon index.js
> 
> [nodemon] 1.11.0
> [nodemon] reading config /tmp/mjml-editor/nodemon.json
> [nodemon] to restart at any time, enter `rs`
> [nodemon] ignoring: /tmp/mjml-editor/.git/**/* .nyc_output .sass-cache bower_components coverage /tmp/mjml-editor/node_modules/**/*
> [nodemon] watching: .env /tmp/mjml-editor/src/server/**/* src/routes.js
> [nodemon] watching extensions: js,json
> [nodemon] starting `node index.js`
> [nodemon] child pid: 31252
> [nodemon] watching 8 files
> express-session deprecated req.secret; provide secret option src/server/index.js:71:44
> [APP] listening on port 3333
> 	webpack built 2d6fb7c36967007159c5 in 6909ms
> /tmp/mjml-editor/src/server/socketEvents.js:40
>     var editor = socket.handshake.session.editor;
>                                          ^
> 
> TypeError: Cannot read property 'editor' of undefined
>     at /tmp/mjml-editor/src/server/socketEvents.js:23:78
>     at session (/tmp/mjml-editor/node_modules/express-session/index.js:189:7)
>     at exports.default (/tmp/mjml-editor/src/server/socketEvents.js:23:41)
>     at Namespace.<anonymous> (/tmp/mjml-editor/src/server/index.js:76:31)
>     at emitOne (events.js:96:13)
>     at Namespace.emit (events.js:191:7)
>     at Namespace.emit (/tmp/mjml-editor/node_modules/socket.io/lib/namespace.js:209:10)
>     at /tmp/mjml-editor/node_modules/socket.io/lib/namespace.js:177:14
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
> 

Hi i'm experiencing an issue here, not sure why
-> Node : v7.8.0
-> Npm: 4.2.0
-> Yarn: 0.21.3

steps to reproduce:
-> git clone https://github.com/lohek/mjml-editor.git
-> cd mjml-editor
-> yarn install
-> yarn run dev

**Comment by meriadec** [comment]
Hey, did you create the `.env` file as described [in the README](https://github.com/lohek/mjml-editor#setup) ?

**Comment by chocopowwwa** [comment]
i did, i it still give me the same error message, hmm not sure why

**Comment by chocopowwwa** [comment]
I solved the issue by:

**Comment by chocopowwwa** [comment]
i solved the issue by : 
-> Installing Redis
-> add `SESSION_SECRET` to the env
